# see - https://cloud.google.com/ai-platform/training/docs/reference/rest/v1/projects.jobs#TrainingInput
trainingInput:

  # # cheapest
  # scaleTier: BASIC

  # # single worker with NVIDIA_TESLA_K80
  # scaleTier: BASIC_GPU

  # single worker multi gpu
  scaleTier: CUSTOM
  masterType: n1-standard-4
  masterConfig:
    acceleratorConfig:
      count: 2
      type: NVIDIA_TESLA_K80
