# see - https://cloud.google.com/ai-platform/training/docs/reference/rest/v1/projects.jobs#TrainingInput
trainingInput:
  # multi worker multi gpu
  scaleTier: CUSTOM
  masterType: n1-standard-4
  masterConfig:
    acceleratorConfig:
      count: 2
      type: NVIDIA_TESLA_K80
  workerCount: 2
  workerType: n1-standard-4
  workerConfig:
    acceleratorConfig:
      count: 2
      type: NVIDIA_TESLA_K80